// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwpfyvvqxcdxvicntayr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3cGZ5dnZxeGNkeHZpY250YXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTQxODEsImV4cCI6MjA2MTkzMDE4MX0.oFgr_X2bAe0X3vsJde3lJpDTVaKkmd_yNLVpFo9qFDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);